# Generated by Django 3.2.25 on 2025-08-14 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AideScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.DateTimeField()),
                ('files_changed', models.IntegerField(default=0)),
                ('files_added', models.IntegerField(default=0)),
                ('files_removed', models.IntegerField(default=0)),
                ('last_run', models.DateTimeField(default=datetime.date.today)),
                ('files_affected', models.IntegerField(default=0)),
                ('output', models.TextField()),
                ('report_file', models.CharField(max_length=255)),
            ],
        ),
    ]
