# Generated by Django 5.2.6 on 2025-10-17 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AideScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
                ('run_time', models.DateTimeField()),
                ('files_changed', models.IntegerField(default=0)),
                ('files_added', models.IntegerField(default=0)),
                ('files_removed', models.IntegerField(default=0)),
                ('files_affected', models.IntegerField(default=0)),
                ('output', models.TextField()),
                ('report_file', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('host', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='aide_reports/')),
                ('is_read', models.BooleanField(default=False)),
                ('status', models.CharField(default='Changes Detected', max_length=50)),
                ('files_changed', models.IntegerField(default=0)),
                ('files_added', models.IntegerField(default=0)),
                ('files_removed', models.IntegerField(default=0)),
                ('output', models.TextField(blank=True)),
            ],
        ),
    ]
