# Generated by Django 3.2.25 on 2025-08-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidechecker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidescanresult',
            name='last_run',
        ),
    ]
