# Generated by Django 3.2.25 on 2025-08-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidechecker', '0002_remove_aidescanresult_last_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidescanresult',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
