# Generated by Django 3.2.25 on 2025-09-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidechecker', '0003_aidescanresult_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidescanresult',
            name='report_file',
        ),
    ]
